/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sewamobil;

import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
/**
 *
 * @author nopal
 */
public class Sewa extends javax.swing.JFrame {

    /**
     * Creates new form Sewa
     */
    public Sewa() {
        initComponents();
        
        
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        Txtsewa = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtTanggal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CmbKode = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        TxtKendaraan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtHarga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtLama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtTotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\nopal\\Documents\\ABSTRACT_BACKGROUND_01.jpg")); // NOI18N
        jLabel14.setText("jLabel14");

        Txtsewa.setIcon(new javax.swing.ImageIcon("C:\\Users\\nopal\\Downloads\\download (3).jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 480, 110, 30);

        jButton3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jButton3.setText("KELUAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(130, 480, 100, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("APLIKASI PENITIPAN MOTOR DAN MOBIL");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(150, 10, 380, 16);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setText("NO TRANSAKSI");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 70, 140, 26);
        getContentPane().add(TxtNo);
        TxtNo.setBounds(190, 70, 150, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setText("TANGGAL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 70, 110, 26);
        getContentPane().add(TxtTanggal);
        TxtTanggal.setBounds(460, 70, 200, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("KODE KENDARAAN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 120, 180, 20);

        CmbKode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kendaraan", "M01", "M02" }));
        CmbKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbKodeActionPerformed(evt);
            }
        });
        getContentPane().add(CmbKode);
        CmbKode.setBounds(190, 120, 150, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setText("JENIS KENDARAAN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 170, 180, 26);
        getContentPane().add(TxtKendaraan);
        TxtKendaraan.setBounds(190, 170, 150, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("HARGA/JAM");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 220, 160, 26);
        getContentPane().add(TxtHarga);
        TxtHarga.setBounds(190, 220, 150, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setText("LAMA");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 270, 90, 16);

        TxtLama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtLamaKeyPressed(evt);
            }
        });
        getContentPane().add(TxtLama);
        TxtLama.setBounds(190, 270, 150, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel7.setText("TOTAL BAYAR");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 320, 140, 26);
        getContentPane().add(TxtTotal);
        TxtTotal.setBounds(190, 320, 150, 22);

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel9.setText("NAUFAL.R");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(420, 430, 210, 33);

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel10.setText("XII RPL 4");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(420, 470, 110, 33);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-mm-dd");
        Calendar cal= Calendar.getInstance();
        TxtTanggal.setText(sdf.format(cal.getTime()));
    }//GEN-LAST:event_formWindowActivated

    private void CmbKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbKodeActionPerformed
        // TODO add your handling code here:
        if (CmbKode.getSelectedItem().equals("M01")){
        TxtKendaraan.setText("Motor");
        TxtHarga.setText("3000");
        
        }else{
        TxtKendaraan.setText("Mobil");
        TxtHarga.setText("10.0000");
        }
    }//GEN-LAST:event_CmbKodeActionPerformed

    private void TxtLamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtLamaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
        int harga = Integer.parseInt(TxtHarga.getText());
        int lama = Integer.parseInt(TxtLama.getText());
        int biaya = (harga*lama);
        TxtTotal.setText(Integer.toString(biaya));
        }
    }//GEN-LAST:event_TxtLamaKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TxtNo.setText("");
        TxtKendaraan.setText("");
        TxtLama.setText("");
        TxtHarga.setText("");
        TxtTotal.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int result=JOptionPane.showConfirmDialog(rootPane,"APAKAH ANDA MAU KELUAR");
        if (result==JOptionPane.YES_NO_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbKode;
    private javax.swing.JTextField TxtHarga;
    private javax.swing.JTextField TxtKendaraan;
    private javax.swing.JTextField TxtLama;
    private javax.swing.JTextField TxtNo;
    private javax.swing.JTextField TxtTanggal;
    private javax.swing.JTextField TxtTotal;
    private javax.swing.JLabel Txtsewa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
